// Automatically generated by the res2go IDE plug-in.
package main

import (
	"PycUncode/PycUncodeVlc"
	"github.com/ying32/govcl/vcl"
)

func main() {
	//var Path, _ = Utils.ListDir("/Volumes/D/GolangTool/PycUncode/test/pyc")
	//if len(Path.Struct) <= 0{
	//	//vcl.ShowMessage("Struct文件不存在")
	//}
	//StrUctByte := Utils.OpenFile(Path.Struct)
	//for _, TempPyc := range Path.Pyc {
	//	var NewPyc []byte
	//	TempPycType := Utils.OpenFile(TempPyc.FullPath)
	//	NewPyc = append(NewPyc, StrUctByte[0:16]...)
	//	NewPyc = append(NewPyc, TempPycType[12:len(TempPycType)]...)
	//	Utils.CreateFileWithDir(TempPyc.Path+TempPyc.Name+".py",NewPyc)
	//}
	vcl.Application.SetScaled(true)
	vcl.Application.SetTitle("project1")
	vcl.Application.Initialize()
	vcl.Application.SetMainFormOnTaskBar(true)
	vcl.Application.CreateForm(&PycUncodeVlc.Main)
	vcl.Application.Run()
}
